Add Github Actions for Windows
rust-av/rav1e-by-gop pull request #1
Opened 2019-12-02 17:37 UTC by Luni-4

2019-12-02 18:22 UTC, lu-zero commented
https://gitlab.redox-os.org/redox-os/termion/merge_requests/151 has some support that needs an overhaul.

2019-12-02 18:23 UTC, lu-zero commented
We could consider https://github.com/mitsuhiko/console as an alternative?

2019-12-02 21:24 UTC, Luni-4 commented
> We could consider https://github.com/mitsuhiko/console as an alternative?

Yep, it could be a good alternative for now, waiting for the `termion`'s PR to land

2019-12-03 13:31 UTC, shssoichiro commented
There are still some issues with the progress indicators anyway. I haven't found a good way to handle having multiple progress indicators that load one at a time. The main issue that still exists with the approach I'm using with termion is that once the segments get to the bottom of the terminal window, they start to overwrite each other and become unreadable.

There's an odd chance this might fix that issue as well? :crossed_fingers: And if it fixes Windows builds too, then I'm for it.

2019-12-03 13:31 UTC, shssoichiro approved these changes

2019-12-03 14:11 UTC, Luni-4 commented
> There's an odd chance this might fix that issue as well? crossed_fingers 

Hmm, I haven't verified that. Have you tested this kind of problem with a particular piece of code? If it's so, could you please share it? Thanks!

2019-12-03 14:18 UTC, shssoichiro commented
It's reproducible in master but requires a long enough video that the progress indicators will vertically reach the bottom of the terminal. For example, I have an encode currently in progress:

![Screenshot_20191203_091633](https://user-images.githubusercontent.com/5951392/70058833-a6315d80-15ad-11ea-9041-4144f522b9a9.png)

Once this hits around segment 60 (i.e. the bottom of the terminal), the remaining segments will start overwriting each other at the bottom of the terminal, instead of creating new lines.

I haven't had a chance to test it with this branch yet.

2019-12-03 18:10 UTC, shssoichiro requested changes
This did not fix the issue with the progress bars hitting the bottom of the terminal window. I'll probably have to do something more creative to resolve that--i.e. not displaying 400 lines of progress. :thinking: 

Anyway, 1 small issue found, below.

2019-12-03 18:10 UTC, shssoichiro commented on src/encode.rs
> +            .move_cursor_to(1, (keyframes.len() as u16 + 5) as usize)
It looks like in the console crate, the cursor indices are 0-indexed, while in termion they were 1-indexed. Would you mind correcting these?

2019-12-03 22:46 UTC, Luni-4 commented
> This did not fix the issue with the progress bars hitting the bottom of the terminal window. I'll probably have to do something more creative to resolve that--i.e. not displaying 400 lines of progress.

I haven't run it myself yet, I will do that later. But are you sure this problem isn't caused by your terminal? Have you tried to use another one?

2019-12-04 00:08 UTC, shssoichiro commented
It's possible. I don't have a different terminal emulator to test with at the moment. Although, it's not caused by this patch (it's possibly just a limitation of this method of interacting with the terminal, which was the same in master).

2019-12-04 00:09 UTC, shssoichiro approved these changes

2019-12-04 00:11 UTC, merged